{% set name = "json_tricks" %}
{% set version = "3.12.1" %}
{% set nbuild = 0 %}
{% set sha256 = "9c01ded56150c73d909ed14305771cf1fce839b7d40f35a1ba0e62258a16d67d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ nbuild }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - pytz

test:
  imports:
    - json_tricks

about:
  home: https://github.com/mverleg/pyjson_tricks
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Extra features for Python''s JSON: comments, order, numpy, pandas, datetimes, and many more! Simple but customizable.'

  description: |
    The pyjson-tricks package brings several pieces of functionality to python handling of json files:
    (1) store and load numpy arrays in human-readable format;
    (2) store and load class instances both generic and customized;
    (3) store and load date/times as a dictionary (including timezone);
    (4) preserve map order {} using OrderedDict;
    (5) allow for comments in json files by starting lines with #;
    (6) sets, complex numbers, decimal, fraction, enums, compression, duplicate keys, etc.
    As well as compression and disallowing duplicate keys.
  doc_url: http://json-tricks.readthedocs.io/en/latest/
  dev_url: https://github.com/mverleg/pyjson_tricks

extra:
  recipe-maintainers:
    - jhkennedy
